### PR TITLE
pit-cs: Remove extra goroutine and Mutex

### PR DESCRIPTION
**Pull request by zjkmxy**
Ref: #38

### CODE REVIEW

**Comment by pulsejet** [comment]
This deadlocks for some reason, but only when I have multiple faces/producers. Any ideas why?

**Comment by zjkmxy** [comment]
I have no idea. Could you show me how you run it?

**Comment by pulsejet** [comment]
Just running two ndnputchunks on different prefixes using a 1G file. Then two ndncatchunks in parallel for both the files.

**Comment by zjkmxy** [comment]
Thanks. Let me have a try.

**Comment by zjkmxy** [comment]
Unfortunately I cannot reproduce this on my computer.

**Comment by zjkmxy** [comment]
Another possible reason could be that there are too many expiring entries that blocks the channel `expiringPitEntries`.
I cannot reproduce it because my Mac is slow and this case never happens.
Let me try to fix this.

**Comment by zjkmxy** [comment]
Hello. I pushed another commit. Please see if it fixes the problem.

**Comment by pulsejet** [comment]
@zjkmxy doesn't lock up for me anymore, but I'm trying to figure out why performance is 25-50% worse. Right now it seems to me that map deletes are simply slow, so doing them on the same thread makes it slower.

But that's unrelated to this PR, so this looks good to me.

**Comment by zjkmxy** [comment]
> @zjkmxy doesn't lock up for me anymore, but I'm trying to figure out why performance is 25-50% worse. Right now it seems to me that map deletes are simply slow, so doing them on the same thread makes it slower.
> 
> But that's unrelated to this PR, so this looks good to me.

OK. Let me see if there is solution.
BTW, I guess ndnputchunks does not provide PIT Token? It seems that PITToken is not used when I run the scenario.

**Comment by pulsejet** [comment]
Right ... maybe I need to stop testing with ndnputchunks

What I currently observe is that if I comment the following line then the aggregate throughput with two instances of putchunks-catchunks, the throughput (content store off) goes from ~3gbps to ~4.5gbps
https://github.com/named-data/YaNFD/blob/79b7e56d00715a9dc8f447ba68dfaec5dfc2f155/table/pit-cs-tree.go#L333

Though I realise now that this could simply be because of the increased GC overhead ...

**Comment by zjkmxy** [comment]
> Right ... maybe I need to stop testing with ndnputchunks
> 
> What I currently observe is that if I comment the following line then the aggregate throughput with two instances of putchunks-catchunks, the throughput (content store off) goes from ~3gbps to ~4.5gbps
> 
> https://github.com/named-data/YaNFD/blob/79b7e56d00715a9dc8f447ba68dfaec5dfc2f155/table/pit-cs-tree.go#L333
> 
> Though I realise now that this could simply be because of the increased GC overhead ...

Another possibility is YaNFD does not use PIT Token due to bugs. I'm not sure if this is the case.

**Comment by zjkmxy** [comment]
Since this PR is closed. Let's continue further discussion (if there is) on #42.

**Pull request merged**
