### PR TITLE
interest: update ForwardingHint format

### PR DESCRIPTION
**Pull request by yoursunny**

### CODE REVIEW

**Comment by yoursunny** [comment]
This is marked as draft because it's not yet tested for interoperability with other libraries and applications.
Please give feedback on the design.

**Comment by yoursunny** [comment]
This has been tested with ndnpeek.
https://gerrit.named-data.net/c/ndn-tools/+/6565 patchset 1

**Review by zjkmxy — APPROVED** [review]
I will merge this when other libraries are ready.

**Comment by yoursunny** [comment]
No need to wait for other libraries.
This implementation supports both formats.

**Pull request merged**
